# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SYSU-TreeHole' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SYSU-TreeHole
  platform :ios, '8.0'
  pod 'AFNetworking', '~> 3.0'
end
